services:
  db:
    image: postgres:13.13
    environment:
      POSTGRES_PASSWORD: foobarhogepiyo
    ports:
      - "25432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8888:8080"
volumes:
  data: